version: '3.8'

services:
  http:
    build: ./http
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    depends_on:
      - script
      - data

  script:
    build: ./script
    volumes:
      - ./app:/app
    depends_on:
      - data

  data:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    volumes:
      - db_data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d

volumes:
  db_data:
